#nginx:
#  container_name: tech_poc_container
#  image: tech_poc_image
#  ports:
#    - 80:80
#    - 443:443

version: '3.8'
services:

  db-postgres:
    build: ./database
    container_name: db-postgres
    ports:
      - 5432:5432
    restart: always

  backend-app:
    build: ./backend
    container_name: backend
    environment:
      - DB_SERVER=db-postgres
      - POSTGRES_DB=postgres
    ports:
      - 8080:8080
    links:
      - db-postgres
    restart: always

  reverse-proxy:
    build: ./proxy
    container_name: reverse-proxy
    ports:
      - 9000:9000
    restart: always

  frontend-elm:
    depends_on:
      - reverse-proxy
    build: ./frontend/elm
    container_name: frontend-elm
    links:
      - backend-app
    restart: always

  frontend-flutter:
    depends_on:
      - reverse-proxy
    build: ./frontend/flutter
    container_name: frontend-flutter
    links:
      - backend-app
    restart: always

  frontend-vue:
    depends_on:
      - reverse-proxy
    build: ./frontend/vue
    container_name: frontend-vue
    links:
      - backend-app
    restart: always

volumes:
  postgres-data: